name: 'CSS Analytics Diff'
description: 'Take CSS and get the changes per CSS Analytics metric'
author: 'Bart Veneman (ProjectWallace.com)'

inputs:
  github-token:
    required: true
  project-wallace-token:
    description: 'Webhook token of the project on ProjectWallace.com'
    required: true
  post-pr-comment:
    description: Whether this action should post a comment to the PR with changes
    required: true
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'bar-chart-2'
